name: build-www
on: push

jobs:
  check_branch:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.check_step.outputs.branch }}
      reponame: ${{ steps.check_step.outputs.reponame }}
      tag: ${{ steps.check_step.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get branch name, etc.
        id: check_step
        run: |
          raw=${{ github.repository }}
          reponame=${raw##*/}
          echo "reponame=$reponame" >> $GITHUB_OUTPUT
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw##*/}
          echo "branch=$branch" >> $GITHUB_OUTPUT
          tag=""
          if [ ${{ github.ref_type }} = "tag" ]; then
            tag=${{ github.ref_name }}
            echo "Running in $reponame on $branch for $tag"
          else
            echo "Running in $reponame on $branch"
          fi
          echo "tag=$tag" >> $GITHUB_OUTPUT

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: check_branch
    env:
      HAVE_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN != '' }}
      CAN_PUBLISH: ${{ secrets.ACCESS_TOKEN != '' }}
      CIWORKFLOW: yes
      CI_SHA1: ${{ github.sha }}
      CI_BUILD_NUM: ${{ github.run_number }}
      CI_PROJECT_USERNAME: ${{ github.repository_owner }}
      CI_PROJECT_REPONAME: ${{ needs.check_branch.outputs.reponame }}
      CI_BRANCH: ${{ needs.check_branch.outputs.branch }}
      CI_TAG: ${{ needs.check_branch.outputs.tag }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build the website
        run: |
          ./gradlew --warning-mode all publish

      - name: Checkout docs
        if: ${{ env.HAVE_ACCESS_TOKEN == 'true' && env.CI_BRANCH == 'main' }}
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner}}/docs
          path: "docs"
          ref: "gh-pages"

       - name: print versions
         run: |
          GUIDEVER=`jq -r .version documentation/build/userguide/details.json`
          REFVER=`jq -r .version documentation/build/reference/details.json`
          echo Guide: $GUIDEVER, reference: $REFVER

#      - name: Update user guide
#        run: |
#          GUIDEVER=`cat documentation/build/userguide/version`
#          rm -rf docs/docs/userguide/current
#          rm -rf docs/docs/userguide/$GUIDEVER
#          rsync -ar documentation/build/userguide/ docs/docs/userguide/current/
#          rsync -ar documentation/build/userguide/ docs/docs/userguide/$GUIDEVER/
#
#      - name: Update reference
#        run: |
#          REFVER=`cat documentation/build/reference/version`
#          rm -rf docs/docs/reference/current
#          rm -rf docs/docs/reference/$REFVER
#          rsync -ar documentation/build/reference/ docs/docs/reference/current/
#          rsync -ar documentation/build/reference/ docs/docs/reference/$REFVER/
#
#      - name: Deploy updated user guide
#        if: ${{ env.HAVE_ACCESS_TOKEN == 'true' && env.CI_BRANCH == 'main' }}
#        uses: JamesIves/github-pages-deploy-action@v4.6.4
#        with:
#          folder: docs/docs/userguide
#          token: ${{ secrets.ACCESS_TOKEN }}
#          repository-name: ${{ github.repository_owner}}/docs
#          branch: gh-pages
#          target-folder: /docs/userguide
#
#      - name: Deploy updated reference
#        if: ${{ env.HAVE_ACCESS_TOKEN == 'true' && env.CI_BRANCH == 'main' }}
#        uses: JamesIves/github-pages-deploy-action@v4.6.4
#        with:
#          folder: docs/docs/reference
#          token: ${{ secrets.ACCESS_TOKEN }}
#          repository-name: ${{ github.repository_owner}}/docs
#          branch: gh-pages
#          target-folder: /docs/reference
